AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Glue Crawler for Admin Console Data'

Parameters:
  AccountId:
    Type: String
    Default: !Ref AWS::AccountId

Resources:
  # Glue Database
  AdminConsoleDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: admin_console_db
        Description: Database for Admin Console monitoring data

  # Glue Crawler
  AdminConsoleDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: admin-console-data-crawler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/QuickSightAdminConsole2025
      DatabaseName: !Ref AdminConsoleDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/
            Exclusions:
              - "**/_SUCCESS"
              - "**/.*"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: |
        {
          "Version": 1.0,
          "CrawlerOutput": {
            "Partitions": {"AddOrUpdateBehavior": "InheritFromTable"}
          }
        }
      Schedule:
        ScheduleExpression: "cron(0 6 * * ? *)"

  # Crawler for CloudWatch metrics data
  MetricStreamsCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: cloudwatch-metrics-crawler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/QuickSightAdminConsole2025
      DatabaseName: !Ref AdminConsoleDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://cw_qs_ds_${AWS::AccountId}/
          - Path: !Sub s3://cw_qs_dash_visual_${AWS::AccountId}/
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

Outputs:
  DatabaseName:
    Description: Glue Database Name
    Value: !Ref AdminConsoleDatabase
  
  CrawlerName:
    Description: Main Crawler Name
    Value: !Ref AdminConsoleDataCrawler