terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# Glue Database
resource "aws_glue_catalog_database" "admin_console_db" {
  name = "admin-console-2025"
}

# Group Membership Table
resource "aws_glue_catalog_table" "group_membership" {
  name          = "group_membership"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "group and user information which is generated by the etl_job_admin_suite_assets_access glue job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-console-new-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/group_membership"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "account_id"
      type    = "string"
      comment = "aws account_id"
    }
    columns {
      name    = "namespace"
      type    = "string"
      comment = "quicksight namespace"
    }
    columns {
      name    = "group"
      type    = "string"
      comment = "quicksight group"
    }
    columns {
      name    = "user"
      type    = "string"
      comment = "quicksight user"
    }
    columns {
      name    = "email"
      type    = "string"
      comment = "email of quicksight user"
    }
    columns {
      name    = "role"
      type    = "string"
      comment = "role of quicksight user: admin, author, reader"
    }
    columns {
      name    = "identity_type"
      type    = "string"
      comment = "identity_type of quicksight user: IAM, quicksight"
    }
    columns {
      name    = "user_arn"
      type    = "string"
      comment = "arn of user"
    }
  }
}

# Object Access Table
resource "aws_glue_catalog_table" "object_access" {
  name          = "object_access"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "objects and access information which is generated by the etl_job_admin_suite_assets_access glue job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-console-new-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/object_access"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "account_id"
      type    = "string"
      comment = "aws account_id"
    }
    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "object_type"
      type    = "string"
      comment = "quicksight object type: dashboard, dataset and etc.."
    }
    columns {
      name    = "object_name"
      type    = "string"
      comment = "quicksight object name"
    }
    columns {
      name    = "object_id"
      type    = "string"
      comment = "quicksight object id"
    }
    columns {
      name    = "principal_type"
      type    = "string"
      comment = "quicksight principal type"
    }
    columns {
      name    = "principal_name"
      type    = "string"
      comment = "quicksight principal name"
    }
    columns {
      name    = "arn"
      type    = "string"
      comment = "quicksight principal arn"
    }
    columns {
      name    = "namespace"
      type    = "string"
      comment = "quicksight namespace"
    }
    columns {
      name    = "permissions"
      type    = "string"
      comment = "access permissions of quicksight objects: who can do what on a dashboard"
    }
  }
}

# Datasets Properties Table
resource "aws_glue_catalog_table" "datasets_properties" {
  name          = "datasets_properties"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "datasets properties information which is generated by the etl_job_admin_suite_ds_properties job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"           = "csv"
    "skip.header.line.count"   = "1"
  }

  storage_descriptor {
    location      = "s3://admin-console-new-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/datasets_properties"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "dataset_id"
      type    = "string"
      comment = "dataset id"
    }
    columns {
      name    = "name"
      type    = "string"
      comment = "dataset name"
    }
    columns {
      name    = "last_updated_time"
      type    = "string"
      comment = "last updated time"
    }
    columns {
      name    = "import_mode"
      type    = "string"
      comment = "import mode (SPICE or DIRECT_QUERY)"
    }
    columns {
      name    = "consumed_spice_capacity_bytes"
      type    = "string"
      comment = "consumed SPICE capacity in bytes"
    }
    columns {
      name    = "rows_ingested"
      type    = "string"
      comment = "rows ingested"
    }
    columns {
      name    = "rows_dropped"
      type    = "string"
      comment = "rows dropped"
    }
    columns {
      name    = "refresh_triggered_time"
      type    = "string"
      comment = "refresh triggered time"
    }
    columns {
      name    = "refresh_time_seconds"
      type    = "string"
      comment = "refresh time in seconds"
    }
    columns {
      name    = "request_source"
      type    = "string"
      comment = "request source"
    }
    columns {
      name    = "request_type"
      type    = "string"
      comment = "request type"
    }
    columns {
      name    = "ingestion_status"
      type    = "string"
      comment = "ingestion status"
    }
    columns {
      name    = "error_info_type"
      type    = "string"
      comment = "error info type"
    }
    columns {
      name    = "error_info_message"
      type    = "string"
      comment = "error info message"
    }
    columns {
      name    = "principal_type"
      type    = "string"
      comment = "principal type"
    }
    columns {
      name    = "principal"
      type    = "string"
      comment = "principal name"
    }
    columns {
      name    = "additional_info"
      type    = "string"
      comment = "additional info"
    }
    columns {
      name    = "actions"
      type    = "string"
      comment = "actions"
    }
    columns {
      name    = "is_file"
      type    = "string"
      comment = "is file indicator"
    }
  }
}

# Datasource Property Table
resource "aws_glue_catalog_table" "datasource_property" {
  name          = "datasource_property"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "QuickSight dataset to datasource dependency mapping"

  table_type = "EXTERNAL_TABLE"

  storage_descriptor {
    location      = "s3://admin-console-new-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/datasource_property"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "region"
      type    = "string"
      comment = "AWS region"
    }
    columns {
      name    = "datasource_name"
      type    = "string"
      comment = "data source name"
    }
    columns {
      name    = "datasource_id"
      type    = "string"
      comment = "data source ID"
    }
    columns {
      name    = "dataset_name"
      type    = "string"
      comment = "dataset name"
    }
    columns {
      name    = "datasource_type"
      type    = "string"
      comment = "data source type"
    }
    columns {
      name    = "dataset_id"
      type    = "string"
      comment = "dataset ID"
    }
    columns {
      name    = "dataset_last_updated_time"
      type    = "string"
      comment = "dataset last updated time"
    }
    columns {
      name    = "dataset_created_time"
      type    = "string"
      comment = "dataset created time"
    }
  }
}