terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# Glue Database
resource "aws_glue_catalog_database" "admin_console_db" {
  name = "admin-console-2025"
}

# Group Membership Table
resource "aws_glue_catalog_table" "group_membership" {
  name          = "group_membership"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "group and user information which is generated by the etl_job_admin_suite_assets_access glue job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/assets_access/group_membership"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "account_id"
      type    = "string"
      comment = "aws account_id"
    }
    columns {
      name    = "namespace"
      type    = "string"
      comment = "quicksight namespace"
    }
    columns {
      name    = "group"
      type    = "string"
      comment = "quicksight group"
    }
    columns {
      name    = "user"
      type    = "string"
      comment = "quicksight user"
    }
    columns {
      name    = "email"
      type    = "string"
      comment = "email of quicksight user"
    }
    columns {
      name    = "role"
      type    = "string"
      comment = "role of quicksight user: admin, author, reader"
    }
    columns {
      name    = "identity_type"
      type    = "string"
      comment = "identity_type of quicksight user: IAM, quicksight"
    }
    columns {
      name    = "user_arn"
      type    = "string"
      comment = "arn of user"
    }
  }
}

# Object Access Table
resource "aws_glue_catalog_table" "object_access" {
  name          = "object_access"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "objects and access information which is generated by the etl_job_admin_suite_assets_access glue job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/assets_access/object_access"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "account_id"
      type    = "string"
      comment = "aws account_id"
    }
    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "object_type"
      type    = "string"
      comment = "quicksight object type: dashboard, dataset and etc.."
    }
    columns {
      name    = "object_name"
      type    = "string"
      comment = "quicksight object name"
    }
    columns {
      name    = "object_id"
      type    = "string"
      comment = "quicksight object id"
    }
    columns {
      name    = "principal_type"
      type    = "string"
      comment = "quicksight principal type"
    }
    columns {
      name    = "principal_name"
      type    = "string"
      comment = "quicksight principal name"
    }
    columns {
      name    = "arn"
      type    = "string"
      comment = "quicksight principal arn"
    }
    columns {
      name    = "namespace"
      type    = "string"
      comment = "quicksight namespace"
    }
    columns {
      name    = "permissions"
      type    = "string"
      comment = "access permissions of quicksight objects: who can do what on a dashboard"
    }
  }
}

# Datasets Properties Table
resource "aws_glue_catalog_table" "datasets_properties" {
  name          = "datasets_properties"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "datasets properties information which is generated by the etl_job_admin_suite_ds_properties job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"           = "csv"
    "skip.header.line.count"   = "1"
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/dataset/datasets_properties"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "dataset_id"
      type    = "string"
      comment = "dataset id"
    }
    columns {
      name    = "name"
      type    = "string"
      comment = "dataset name"
    }
    columns {
      name    = "last_updated_time"
      type    = "string"
      comment = "last updated time"
    }
    columns {
      name    = "import_mode"
      type    = "string"
      comment = "import mode (SPICE or DIRECT_QUERY)"
    }
    columns {
      name    = "consumed_spice_capacity_bytes"
      type    = "string"
      comment = "consumed SPICE capacity in bytes"
    }
    columns {
      name    = "rows_ingested"
      type    = "string"
      comment = "rows ingested"
    }
    columns {
      name    = "rows_dropped"
      type    = "string"
      comment = "rows dropped"
    }
    columns {
      name    = "refresh_triggered_time"
      type    = "string"
      comment = "refresh triggered time"
    }
    columns {
      name    = "refresh_time_seconds"
      type    = "string"
      comment = "refresh time in seconds"
    }
    columns {
      name    = "request_source"
      type    = "string"
      comment = "request source"
    }
    columns {
      name    = "request_type"
      type    = "string"
      comment = "request type"
    }
    columns {
      name    = "ingestion_status"
      type    = "string"
      comment = "ingestion status"
    }
    columns {
      name    = "error_info_type"
      type    = "string"
      comment = "error info type"
    }
    columns {
      name    = "error_info_message"
      type    = "string"
      comment = "error info message"
    }
    columns {
      name    = "is_file"
      type    = "string"
      comment = "is file indicator"
    }
  }
}

# Folder Assets Table
resource "aws_glue_catalog_table" "folder_assets" {
  name          = "folder_assets"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "folder assets information which is generated by the etl_job_admin_suite_folder_assets job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/folder_assets/folder_assets"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "folder_id"
      type    = "string"
      comment = "folder id"
    }
    columns {
      name    = "member_id"
      type    = "string"
      comment = "member id"
    }
  }
}

# Folder LK Table
resource "aws_glue_catalog_table" "folder_lk" {
  name          = "folder_lk"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "folder permissions information which is generated by the etl_job_admin_suite_folder_assets job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/folder_assets/folder_lk"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "account_id"
      type    = "string"
      comment = "aws account_id"
    }
    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "object_type"
      type    = "string"
      comment = "object type"
    }
    columns {
      name    = "folder_name"
      type    = "string"
      comment = "folder name"
    }
    columns {
      name    = "folder_id"
      type    = "string"
      comment = "folder id"
    }
    columns {
      name    = "folder_arn"
      type    = "string"
      comment = "folder arn"
    }
    columns {
      name    = "principal_type"
      type    = "string"
      comment = "principal type"
    }
    columns {
      name    = "principal_name"
      type    = "string"
      comment = "principal name"
    }
    columns {
      name    = "additional_info"
      type    = "string"
      comment = "additional info"
    }
    columns {
      name    = "actions"
      type    = "string"
      comment = "actions"
    }
  }
}

# Folder Path Table
resource "aws_glue_catalog_table" "folder_path" {
  name          = "folder_path"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "folder path information which is generated by the etl_job_admin_suite_folder_assets job"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "has_encrypted_data" = "false"
    "classification"     = "csv"
    "areColumnsQuoted"   = "false"
    "typeOfData"         = "file"
    "columnsOrdered"     = "true"
    "delimiter"          = ","
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/folder_assets/folder_path"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "folder_id"
      type    = "string"
      comment = "folder id"
    }
    columns {
      name    = "folder_name"
      type    = "string"
      comment = "folder name"
    }
    columns {
      name    = "folder_path"
      type    = "string"
      comment = "folder path"
    }
  }
}

# CloudTrail Logs Table
resource "aws_glue_catalog_table" "cloudtrail_logs" {
  name          = "cloudtrail_logs_pp"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "cloudtrail logs"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"                        = "cloudtrail"
    "projection.enabled"                    = "true"
    "projection.region.type"                = "enum"
    "projection.region.values"              = "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-central-1,ap-southeast-1,ap-southeast-2,ap-northeast-1,ap-northeast-2,sa-east-1"
    "projection.timestamp.type"             = "date"
    "projection.timestamp.format"           = "yyyy/MM/dd"
    "projection.timestamp.range"            = "${var.start_date_parameter},NOW"
    "projection.timestamp.interval"         = "1"
    "projection.timestamp.interval.unit"    = "DAYS"
    "storage.location.template"             = "${var.cloudtrail_location}/$${region}/$${timestamp}"
  }

  partition_keys {
    name    = "region"
    type    = "string"
    comment = "aws_region"
  }
  partition_keys {
    name    = "timestamp"
    type    = "string"
    comment = "timestamp"
  }

  storage_descriptor {
    location      = var.cloudtrail_location
    input_format  = "com.amazon.emr.cloudtrail.CloudTrailInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "com.amazon.emr.hive.serde.CloudTrailSerde"
    }

    columns {
      name    = "eventversion"
      type    = "string"
      comment = "eventversion"
    }
    columns {
      name    = "useridentity"
      type    = "struct<type:string,principalid:string,arn:string,accountid:string,invokedby:string,accesskeyid:string,username:string,sessioncontext:struct<attributes:struct<mfaauthenticated:string,creationdate:string>,sessionissuer:struct<type:string,principalid:string,arn:string,accountid:string,username:string>>>"
      comment = "useridentity"
    }
    columns {
      name    = "eventtime"
      type    = "string"
      comment = "eventtime"
    }
    columns {
      name    = "eventsource"
      type    = "string"
      comment = "eventsource"
    }
    columns {
      name    = "eventname"
      type    = "string"
      comment = "eventname"
    }
    columns {
      name    = "awsregion"
      type    = "string"
      comment = "awsregion"
    }
    columns {
      name    = "sourceipaddress"
      type    = "string"
      comment = "sourceipaddress"
    }
    columns {
      name    = "useragent"
      type    = "string"
      comment = "useragent"
    }
    columns {
      name    = "errorcode"
      type    = "string"
      comment = "errorcode"
    }
    columns {
      name    = "errormessage"
      type    = "string"
      comment = "errormessage"
    }
    columns {
      name    = "requestparameters"
      type    = "string"
      comment = "requestparameters"
    }
    columns {
      name    = "responseelements"
      type    = "string"
      comment = "responseelements"
    }
    columns {
      name    = "additionaleventdata"
      type    = "string"
      comment = "additionaleventdata"
    }
    columns {
      name    = "requestid"
      type    = "string"
      comment = "requestid"
    }
    columns {
      name    = "eventid"
      type    = "string"
      comment = "eventid"
    }
    columns {
      name    = "resources"
      type    = "array<struct<arn:string,accountid:string,type:string>>"
      comment = "resources"
    }
    columns {
      name    = "eventtype"
      type    = "string"
      comment = "eventtype"
    }
    columns {
      name    = "apiversion"
      type    = "string"
      comment = "apiversion"
    }
    columns {
      name    = "readonly"
      type    = "string"
      comment = "readonly"
    }
    columns {
      name    = "recipientaccountid"
      type    = "string"
      comment = "recipientaccountid"
    }
    columns {
      name    = "serviceeventdetails"
      type    = "string"
      comment = "serviceeventdetails"
    }
    columns {
      name    = "sharedeventid"
      type    = "string"
      comment = "sharedeventid"
    }
    columns {
      name    = "vpcendpointid"
      type    = "string"
      comment = "vpcendpointid"
    }
  }
}

# Data Dictionary Table
resource "aws_glue_catalog_table" "data_dict" {
  name          = "data_dict"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "data dictionry"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification" = "csv"
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/dataset/data_dictionary"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "datasetname"
      type    = "string"
      comment = "datasetname"
    }
    columns {
      name    = "datasetid"
      type    = "string"
      comment = "datasetid"
    }
    columns {
      name    = "columnname"
      type    = "string"
      comment = "columnname"
    }
    columns {
      name    = "columntype"
      type    = "string"
      comment = "columntype"
    }
    columns {
      name    = "columndesc"
      type    = "string"
      comment = "columndesc"
    }
  }
}

# Datasets Info Table
resource "aws_glue_catalog_table" "datasets_info" {
  name          = "datasets_info"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "datasets info"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification" = "csv"
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/dataset/datasets_info"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = "|"
      }
    }

    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws_region"
    }
    columns {
      name    = "dashboard_name"
      type    = "string"
      comment = "dashboard_name"
    }
    columns {
      name    = "dashboardid"
      type    = "string"
      comment = "dashboardid"
    }
    columns {
      name    = "analysis"
      type    = "string"
      comment = "analysis"
    }
    columns {
      name    = "analysis_id"
      type    = "string"
      comment = "analysis_id"
    }
    columns {
      name    = "dataset_name"
      type    = "string"
      comment = "dataset_name"
    }
    columns {
      name    = "dataset_id"
      type    = "string"
      comment = "dataset_id"
    }
    columns {
      name    = "lastupdatedtime"
      type    = "string"
      comment = "lastupdatedtime"
    }
    columns {
      name    = "data_source_name"
      type    = "string"
      comment = "data_source_name"
    }
    columns {
      name    = "data_source_id"
      type    = "string"
      comment = "data_source_id"
    }
    columns {
      name    = "catalog"
      type    = "string"
      comment = "catalog"
    }
    columns {
      name    = "sqlname/schema"
      type    = "string"
      comment = "sqlname/schema"
    }
    columns {
      name    = "sqlquery/table_name"
      type    = "string"
      comment = "sqlquery/table_name"
    }
  }
}

# Q Topic Info Table
resource "aws_glue_catalog_table" "q_topic_info" {
  name          = "q_topic_info"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "q topics info"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"           = "csv"
    "skip.header.line.count"   = "1"
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/q_md/q_topics_info"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "topic_id"
      type    = "string"
      comment = "topic_id"
    }
    columns {
      name    = "topic_name"
      type    = "string"
      comment = "topic_name"
    }
    columns {
      name    = "dataset_arn"
      type    = "string"
      comment = "dataset_arn"
    }
    columns {
      name    = "dataset_name"
      type    = "string"
      comment = "dataset_name"
    }
    columns {
      name    = "description"
      type    = "string"
      comment = "description"
    }
    columns {
      name    = "user_experience_version"
      type    = "string"
      comment = "user_experience_version"
    }
  }
}

# Q Object Access Table
resource "aws_glue_catalog_table" "q_object_access" {
  name          = "q_object_access"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "q object access"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"           = "csv"
    "skip.header.line.count"   = "1"
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/q_md/q_object_access"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "account_id"
      type    = "string"
      comment = "aws account_id"
    }
    columns {
      name    = "aws_region"
      type    = "string"
      comment = "aws region name"
    }
    columns {
      name    = "object_type"
      type    = "string"
      comment = "quicksight object type: dashboard, dataset and etc.."
    }
    columns {
      name    = "object_name"
      type    = "string"
      comment = "quicksight object name"
    }
    columns {
      name    = "object_id"
      type    = "string"
      comment = "quicksight object id"
    }
    columns {
      name    = "principal_type"
      type    = "string"
      comment = "quicksight principal type"
    }
    columns {
      name    = "principal_name"
      type    = "string"
      comment = "quicksight principal name"
    }
    columns {
      name    = "arn"
      type    = "string"
      comment = "quicksight principal arn"
    }
    columns {
      name    = "namespace"
      type    = "string"
      comment = "quicksight namespace"
    }
    columns {
      name    = "permissions"
      type    = "string"
      comment = "access permissions of quicksight objects: who can do what on a Q topic"
    }
  }
}

# Datasource Property Table
resource "aws_glue_catalog_table" "datasource_property" {
  name          = "datasource_property"
  database_name = aws_glue_catalog_database.admin_console_db.name
  description   = "QuickSight dataset to datasource dependency mapping"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    "classification"           = "csv"
    "skip.header.line.count"   = "1"
  }

  storage_descriptor {
    location      = "s3://admin-suite-${data.aws_caller_identity.current.account_id}/monitoring/quicksight/datasource_property"
    input_format  = "org.apache.hadoop.mapred.TextInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
    compressed    = false

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
      parameters = {
        "field.delim" = ","
      }
    }

    columns {
      name    = "region"
      type    = "string"
      comment = "AWS region"
    }
    columns {
      name    = "datasource_name"
      type    = "string"
      comment = "data source name"
    }
    columns {
      name    = "datasource_id"
      type    = "string"
      comment = "data source ID"
    }
    columns {
      name    = "dataset_name"
      type    = "string"
      comment = "dataset name"
    }
    columns {
      name    = "datasource_type"
      type    = "string"
      comment = "data source type"
    }
    columns {
      name    = "dataset_id"
      type    = "string"
      comment = "dataset ID"
    }
    columns {
      name    = "dataset_last_updated_time"
      type    = "string"
      comment = "dataset last updated time"
    }
    columns {
      name    = "dataset_created_time"
      type    = "string"
      comment = "dataset created time"
    }
  }
}