from aws_cdk import (
    Stack,
    CfnParameter,
    aws_glue as glue,
    aws_athena as athena,
)
from constructs import Construct
from .cloudwatch_tables import create_cloudwatch_tables
from .crawlers import create_crawlers

class QuickAdminSuiteDataModelStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # Parameters
        cloudtrail_location = CfnParameter(
            self, "CloudtrailLocation",
            type="String",
            min_length=1,
            description="Enter the location of your trail as specified in the Cloudtrail console, start with s3://, end with CloudTrail/. example: s3://cloudtrail-awslogs-123456789123-do-not-delete/AWSLogs/123456789123/CloudTrail/"
        )

        start_date_parameter = CfnParameter(
            self, "StartDateParameter",
            type="String",
            min_length=10,
            description="Input the start date for the data in the Cloudtrail bucket in YYYY/MM/DD format. For example, if the earliest data in the bucket is from 1st August 2021, use 2021/08/01"
        )
        
        script_bucket_name = CfnParameter(
            self, "ScriptBucketName",
            type="String",
            default="admin-console-cfn-dataprepare-code",
            description="S3 bucket name containing Glue job scripts"
        )



        # Glue Database
        admin_console_db = glue.CfnDatabase(
            self, "adminconsoledb2025",
            catalog_id=self.account,
            database_input=glue.CfnDatabase.DatabaseInputProperty(
                name="admin-console-2025"
            )
        )

        # Group Membership Table
        group_membership_table = glue.CfnTable(
            self, "groupmembership",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="group and user information which is generated by the etl_job_admin_suite_assets_access glue job",
                name="group_membership",
                parameters={
                    "has_encrypted_data": "false",
                    "classification": "csv",
                    "areColumnsQuoted": "false",
                    "typeOfData": "file",
                    "columnsOrdered": "true",
                    "delimiter": ","
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="account_id", type="string", comment="aws account_id"),
                        glue.CfnTable.ColumnProperty(name="namespace", type="string", comment="quicksight namespace"),
                        glue.CfnTable.ColumnProperty(name="group", type="string", comment="quicksight group"),
                        glue.CfnTable.ColumnProperty(name="user", type="string", comment="quicksight user"),
                        glue.CfnTable.ColumnProperty(name="email", type="string", comment="email of quicksight user"),
                        glue.CfnTable.ColumnProperty(name="role", type="string", comment="role of quicksight user: admin, author, reader"),
                        glue.CfnTable.ColumnProperty(name="identity_type", type="string", comment="identity_type of quicksight user: IAM, quicksight"),
                        glue.CfnTable.ColumnProperty(name="user_arn", type="string", comment="arn of user")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/assets_access/group_membership",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Object Access Table
        object_access_table = glue.CfnTable(
            self, "objectaccess",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="objects and access information which is generated by the etl_job_admin_suite_assets_access glue job",
                name="object_access",
                parameters={
                    "has_encrypted_data": "false",
                    "classification": "csv",
                    "areColumnsQuoted": "false",
                    "typeOfData": "file",
                    "columnsOrdered": "true",
                    "delimiter": ","
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="account_id", type="string", comment="aws account_id"),
                        glue.CfnTable.ColumnProperty(name="aws_region", type="string", comment="aws region name"),
                        glue.CfnTable.ColumnProperty(name="object_type", type="string", comment="quicksight object type: dashboard, dataset and etc.."),
                        glue.CfnTable.ColumnProperty(name="object_name", type="string", comment="quicksight object name"),
                        glue.CfnTable.ColumnProperty(name="object_id", type="string", comment="quicksight object id"),
                        glue.CfnTable.ColumnProperty(name="principal_type", type="string", comment="quicksight principal type"),
                        glue.CfnTable.ColumnProperty(name="principal_name", type="string", comment="quicksight principal name"),
                        glue.CfnTable.ColumnProperty(name="arn", type="string", comment="quicksight principal arn"),
                        glue.CfnTable.ColumnProperty(name="namespace", type="string", comment="quicksight namespace"),
                        glue.CfnTable.ColumnProperty(name="permissions", type="string", comment="access permissions of quicksight objects: who can do what on a dashboard")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/assets_access/object_access",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Datasets Properties Table
        datasets_properties_table = glue.CfnTable(
            self, "datasetsproperties",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="datasets properties information which is generated by the etl_job_admin_suite_ds_properties job",
                name="datasets_properties",
                parameters={
                    "classification": "csv",
                    "skip.header.line.count": "1"
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="region", type="string", comment="aws region name"),
                        glue.CfnTable.ColumnProperty(name="dataset_id", type="string", comment="dataset id"),
                        glue.CfnTable.ColumnProperty(name="name", type="string", comment="dataset name"),
                        glue.CfnTable.ColumnProperty(name="last_updated_time", type="string", comment="last updated time"),
                        glue.CfnTable.ColumnProperty(name="import_mode", type="string", comment="import mode (SPICE or DIRECT_QUERY)"),
                        glue.CfnTable.ColumnProperty(name="consumed_spice_capacity_bytes", type="string", comment="consumed SPICE capacity in bytes"),
                        glue.CfnTable.ColumnProperty(name="rows_ingested", type="string", comment="rows ingested"),
                        glue.CfnTable.ColumnProperty(name="rows_dropped", type="string", comment="rows dropped"),
                        glue.CfnTable.ColumnProperty(name="refresh_triggered_time", type="string", comment="refresh triggered time"),
                        glue.CfnTable.ColumnProperty(name="refresh_time_seconds", type="string", comment="refresh time in seconds"),
                        glue.CfnTable.ColumnProperty(name="request_source", type="string", comment="request source"),
                        glue.CfnTable.ColumnProperty(name="request_type", type="string", comment="request type"),
                        glue.CfnTable.ColumnProperty(name="ingestion_status", type="string", comment="ingestion status"),
                        glue.CfnTable.ColumnProperty(name="error_info_type", type="string", comment="error info type"),
                        glue.CfnTable.ColumnProperty(name="error_info_message", type="string", comment="error info message"),
                        glue.CfnTable.ColumnProperty(name="is_file", type="string", comment="is file indicator")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/dataset/datasets_properties",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Folder Assets Table
        folder_assets_table = glue.CfnTable(
            self, "folderassets",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="folder assets information which is generated by the etl_job_admin_suite_folder_assets job",
                name="folder_assets",
                parameters={
                    "has_encrypted_data": "false",
                    "classification": "csv",
                    "areColumnsQuoted": "false",
                    "typeOfData": "file",
                    "columnsOrdered": "true",
                    "delimiter": ","
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="aws_region", type="string", comment="aws region name"),
                        glue.CfnTable.ColumnProperty(name="folder_id", type="string", comment="folder id"),
                        glue.CfnTable.ColumnProperty(name="member_id", type="string", comment="member id")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/folder_assets/folder_assets",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Folder LK Table
        folder_lk_table = glue.CfnTable(
            self, "folderlk",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="folder permissions information which is generated by the etl_job_admin_suite_folder_assets job",
                name="folder_lk",
                parameters={
                    "has_encrypted_data": "false",
                    "classification": "csv",
                    "areColumnsQuoted": "false",
                    "typeOfData": "file",
                    "columnsOrdered": "true",
                    "delimiter": ","
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="account_id", type="string", comment="aws account_id"),
                        glue.CfnTable.ColumnProperty(name="aws_region", type="string", comment="aws region name"),
                        glue.CfnTable.ColumnProperty(name="object_type", type="string", comment="object type"),
                        glue.CfnTable.ColumnProperty(name="folder_name", type="string", comment="folder name"),
                        glue.CfnTable.ColumnProperty(name="folder_id", type="string", comment="folder id"),
                        glue.CfnTable.ColumnProperty(name="folder_arn", type="string", comment="folder arn"),
                        glue.CfnTable.ColumnProperty(name="principal_type", type="string", comment="principal type"),
                        glue.CfnTable.ColumnProperty(name="principal_name", type="string", comment="principal name"),
                        glue.CfnTable.ColumnProperty(name="additional_info", type="string", comment="additional info"),
                        glue.CfnTable.ColumnProperty(name="actions", type="string", comment="actions")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/folder_assets/folder_lk",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Folder Path Table
        folder_path_table = glue.CfnTable(
            self, "folderpath",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="folder path information which is generated by the etl_job_admin_suite_folder_assets job",
                name="folder_path",
                parameters={
                    "has_encrypted_data": "false",
                    "classification": "csv",
                    "areColumnsQuoted": "false",
                    "typeOfData": "file",
                    "columnsOrdered": "true",
                    "delimiter": ","
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="aws_region", type="string", comment="aws region name"),
                        glue.CfnTable.ColumnProperty(name="folder_id", type="string", comment="folder id"),
                        glue.CfnTable.ColumnProperty(name="folder_name", type="string", comment="folder name"),
                        glue.CfnTable.ColumnProperty(name="folder_path", type="string", comment="folder path")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/folder_assets/folder_path",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # CloudTrail Logs Table
        cloudtrail_table = glue.CfnTable(
            self, "cloudtraillog",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="cloudtrail logs",
                name="cloudtrail_logs_pp",
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="eventversion", type="string", comment="eventversion"),
                        glue.CfnTable.ColumnProperty(name="useridentity", type="struct<type:string,principalid:string,arn:string,accountid:string,invokedby:string,accesskeyid:string,username:string,sessioncontext:struct<attributes:struct<mfaauthenticated:string,creationdate:string>,sessionissuer:struct<type:string,principalid:string,arn:string,accountid:string,username:string>>>", comment="useridentity"),
                        glue.CfnTable.ColumnProperty(name="eventtime", type="string", comment="eventtime"),
                        glue.CfnTable.ColumnProperty(name="eventsource", type="string", comment="eventsource"),
                        glue.CfnTable.ColumnProperty(name="eventname", type="string", comment="eventname"),
                        glue.CfnTable.ColumnProperty(name="awsregion", type="string", comment="awsregion"),
                        glue.CfnTable.ColumnProperty(name="sourceipaddress", type="string", comment="sourceipaddress"),
                        glue.CfnTable.ColumnProperty(name="useragent", type="string", comment="useragent"),
                        glue.CfnTable.ColumnProperty(name="errorcode", type="string", comment="errorcode"),
                        glue.CfnTable.ColumnProperty(name="errormessage", type="string", comment="errormessage"),
                        glue.CfnTable.ColumnProperty(name="requestparameters", type="string", comment="requestparameters"),
                        glue.CfnTable.ColumnProperty(name="responseelements", type="string", comment="responseelements"),
                        glue.CfnTable.ColumnProperty(name="additionaleventdata", type="string", comment="additionaleventdata"),
                        glue.CfnTable.ColumnProperty(name="requestid", type="string", comment="requestid"),
                        glue.CfnTable.ColumnProperty(name="eventid", type="string", comment="eventid"),
                        glue.CfnTable.ColumnProperty(name="resources", type="array<struct<arn:string,accountid:string,type:string>>", comment="resources"),
                        glue.CfnTable.ColumnProperty(name="eventtype", type="string", comment="eventtype"),
                        glue.CfnTable.ColumnProperty(name="apiversion", type="string", comment="apiversion"),
                        glue.CfnTable.ColumnProperty(name="readonly", type="string", comment="readonly"),
                        glue.CfnTable.ColumnProperty(name="recipientaccountid", type="string", comment="recipientaccountid"),
                        glue.CfnTable.ColumnProperty(name="serviceeventdetails", type="string", comment="serviceeventdetails"),
                        glue.CfnTable.ColumnProperty(name="sharedeventid", type="string", comment="sharedeventid"),
                        glue.CfnTable.ColumnProperty(name="vpcendpointid", type="string", comment="vpcendpointid")
                    ],
                    input_format="com.amazon.emr.cloudtrail.CloudTrailInputFormat",
                    location=cloudtrail_location.value_as_string,
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        serialization_library="com.amazon.emr.hive.serde.CloudTrailSerde"
                    ),
                    stored_as_sub_directories=False
                ),
                partition_keys=[
                    glue.CfnTable.ColumnProperty(name="region", type="string", comment="aws_region"),
                    glue.CfnTable.ColumnProperty(name="timestamp", type="string", comment="timestamp")
                ],
                parameters={
                    "classification": "cloudtrail",
                    "projection.enabled": "true",
                    "projection.region.type": "enum",
                    "projection.region.values": "us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1,eu-central-1,ap-southeast-1,ap-southeast-2,ap-northeast-1,ap-northeast-2,sa-east-1",
                    "projection.timestamp.type": "date",
                    "projection.timestamp.format": "yyyy/MM/dd",
                    "projection.timestamp.range": f"{start_date_parameter.value_as_string},NOW",
                    "projection.timestamp.interval": "1",
                    "projection.timestamp.interval.unit": "DAYS",
                    "storage.location.template": f"{cloudtrail_location.value_as_string}/${{region}}/${{timestamp}}"
                },
                table_type="EXTERNAL_TABLE"
            )
        )

        # Data Dictionary Table
        data_dict_table = glue.CfnTable(
            self, "datadict",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="data dictionry",
                name="data_dict",
                parameters={"classification": "csv"},
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="datasetname", type="string", comment="datasetname"),
                        glue.CfnTable.ColumnProperty(name="datasetid", type="string", comment="datasetid"),
                        glue.CfnTable.ColumnProperty(name="columnname", type="string", comment="columnname"),
                        glue.CfnTable.ColumnProperty(name="columntype", type="string", comment="columntype"),
                        glue.CfnTable.ColumnProperty(name="columndesc", type="string", comment="columndesc")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/dataset/data_dictionary",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Datasets Info Table
        datasets_info_table = glue.CfnTable(
            self, "datasetsinfo",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="datasets info",
                name="datasets_info",
                parameters={"classification": "csv"},
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="aws_region", type="string", comment="aws_region"),
                        glue.CfnTable.ColumnProperty(name="dashboard_name", type="string", comment="dashboard_name"),
                        glue.CfnTable.ColumnProperty(name="dashboardid", type="string", comment="dashboardid"),
                        glue.CfnTable.ColumnProperty(name="analysis", type="string", comment="analysis"),
                        glue.CfnTable.ColumnProperty(name="analysis_id", type="string", comment="analysis_id"),
                        glue.CfnTable.ColumnProperty(name="dataset_name", type="string", comment="dataset_name"),
                        glue.CfnTable.ColumnProperty(name="dataset_id", type="string", comment="dataset_id"),
                        glue.CfnTable.ColumnProperty(name="lastupdatedtime", type="string", comment="lastupdatedtime"),
                        glue.CfnTable.ColumnProperty(name="data_source_name", type="string", comment="data_source_name"),
                        glue.CfnTable.ColumnProperty(name="data_source_id", type="string", comment="data_source_id"),
                        glue.CfnTable.ColumnProperty(name="catalog", type="string", comment="catalog"),
                        glue.CfnTable.ColumnProperty(name="sqlname/schema", type="string", comment="sqlname/schema"),
                        glue.CfnTable.ColumnProperty(name="sqlquery/table_name", type="string", comment="sqlquery/table_name")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/dataset/datasets_info",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": "|"},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Q Topic Info Table
        q_topic_info_table = glue.CfnTable(
            self, "qtopicinfo",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="q topics info",
                name="q_topic_info",
                parameters={
                    "classification": "csv",
                    "skip.header.line.count": "1"
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="topic_id", type="string", comment="topic_id"),
                        glue.CfnTable.ColumnProperty(name="topic_name", type="string", comment="topic_name"),
                        glue.CfnTable.ColumnProperty(name="dataset_arn", type="string", comment="dataset_arn"),
                        glue.CfnTable.ColumnProperty(name="dataset_name", type="string", comment="dataset_name"),
                        glue.CfnTable.ColumnProperty(name="description", type="string", comment="description"),
                        glue.CfnTable.ColumnProperty(name="user_experience_version", type="string", comment="user_experience_version")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/q_md/q_topics_info",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Q Object Access Info Table
        q_object_access_table = glue.CfnTable(
            self, "qobjectaccessinfo",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                description="q object access",
                name="q_object_access",
                parameters={
                    "classification": "csv",
                    "skip.header.line.count": "1"
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="account_id", type="string", comment="aws account_id"),
                        glue.CfnTable.ColumnProperty(name="aws_region", type="string", comment="aws region name"),
                        glue.CfnTable.ColumnProperty(name="object_type", type="string", comment="quicksight object type: dashboard, dataset and etc.."),
                        glue.CfnTable.ColumnProperty(name="object_name", type="string", comment="quicksight object name"),
                        glue.CfnTable.ColumnProperty(name="object_id", type="string", comment="quicksight object id"),
                        glue.CfnTable.ColumnProperty(name="principal_type", type="string", comment="quicksight principal type"),
                        glue.CfnTable.ColumnProperty(name="principal_name", type="string", comment="quicksight principal name"),
                        glue.CfnTable.ColumnProperty(name="arn", type="string", comment="quicksight principal arn"),
                        glue.CfnTable.ColumnProperty(name="namespace", type="string", comment="quicksight namespace"),
                        glue.CfnTable.ColumnProperty(name="permissions", type="string", comment="access permissions of quicksight objects: who can do what on a Q topic")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/q_md/q_object_access",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

        # Create CloudWatch tables
        cw_tables = create_cloudwatch_tables(self, admin_console_db)
        
        # Create crawlers
        crawlers = create_crawlers(self, script_bucket_name)

        # Datasource Property Table
        datasource_property_table = glue.CfnTable(
            self, "DatasourcePropertyTable",
            catalog_id=self.account,
            database_name=admin_console_db.ref,
            table_input=glue.CfnTable.TableInputProperty(
                name="datasource_property",
                description="QuickSight dataset to datasource dependency mapping",
                parameters={
                    "classification": "csv",
                    "skip.header.line.count": "1"
                },
                storage_descriptor=glue.CfnTable.StorageDescriptorProperty(
                    columns=[
                        glue.CfnTable.ColumnProperty(name="region", type="string", comment="AWS region"),
                        glue.CfnTable.ColumnProperty(name="datasource_name", type="string", comment="data source name"),
                        glue.CfnTable.ColumnProperty(name="datasource_id", type="string", comment="data source ID"),
                        glue.CfnTable.ColumnProperty(name="dataset_name", type="string", comment="dataset name"),
                        glue.CfnTable.ColumnProperty(name="datasource_type", type="string", comment="data source type"),
                        glue.CfnTable.ColumnProperty(name="dataset_id", type="string", comment="dataset ID"),
                        glue.CfnTable.ColumnProperty(name="dataset_last_updated_time", type="string", comment="dataset last updated time"),
                        glue.CfnTable.ColumnProperty(name="dataset_created_time", type="string", comment="dataset created time")
                    ],
                    compressed=False,
                    input_format="org.apache.hadoop.mapred.TextInputFormat",
                    location=f"s3://admin-suite-{self.account}/monitoring/quicksight/datasource_property",
                    output_format="org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
                    serde_info=glue.CfnTable.SerdeInfoProperty(
                        parameters={"field.delim": ","},
                        serialization_library="org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
                    ),
                    stored_as_sub_directories=False
                ),
                table_type="EXTERNAL_TABLE"
            )
        )

