AWSTemplateFormatVersion: '2010-09-09'
Resources:
  QuickAdminSuiteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: QuickAdminSuiteRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - cloudformation.amazonaws.com
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: QuickSight-AdminConsole-2025
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - iam:*
                  - quicksight:*
                  - glue:*
                  - s3:*
                  - sts:AssumeRole
                  - cloudwatch:*
                  - logs:*
                Resource: '*'
                Effect: Allow
  admin_suite_qs_access_info:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: '3.9'
        ScriptLocation: !Sub s3://admin-console-cfn-dataprepare-code/glue/scripts/2025/admin_suite_qs_access_info.py
      DefaultArguments:
        '--AWS_REGION': !Sub ${AWS::Region}
      GlueVersion: '3.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxCapacity: 1
      MaxRetries: 0
      Name: admin_suite_qs_access_info
      Role: !GetAtt QuickAdminSuiteRole.Arn
      Timeout: 120
    DependsOn:
      - admin_suite_qs_md
    Metadata:
      AWS::CloudFormation::Designer:
        id: c4462e36-ef27-43d6-a0df-01246a77b117
  admin_suite_dataset_dashboard_info:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: '3.9'
        ScriptLocation: !Sub s3://admin-console-cfn-dataprepare-code/glue/scripts/2025/admin_suite_dataset_dashboard_info.py
      DefaultArguments:
        '--AWS_REGION': !Sub ${AWS::Region}
      GlueVersion: '3.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxCapacity: 1
      MaxRetries: 0
      Name: admin_suite_dataset_dashboard_info
      Role: !GetAtt QuickAdminSuiteRole.Arn
      Timeout: 120
    DependsOn:
      - admin_suite_qs_md
    Metadata:
      AWS::CloudFormation::Designer:
        id: c4462e36-ef27-43d6-a0df-01246a77b117
  admin_suite_folder_info:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: '3.9'
        ScriptLocation: s3://admin-console-cfn-dataprepare-code/glue/scripts/2025/adminconsolefolderinfo.py
      DefaultArguments:
        '--AWS_REGION': !Sub ${AWS::Region}
      GlueVersion: '3.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxCapacity: 1
      MaxRetries: 0
      Name: admin_suite_folder_info
      Role: !GetAtt QuickAdminSuiteRole.Arn
      Timeout: 120
    DependsOn:
      - admin_suite_qs_md
  admin_suite_q_access_info:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Sub s3://admin-console-cfn-dataprepare-code/glue/scripts/2025/admin_suite_q_access_info.py
      DefaultArguments:
        '--region': !Sub ${AWS::Region}
        '--aws_account_id': !Sub ${AWS::AccountId}
        '--output_s3_path': !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/q_object_access
      GlueVersion: '5.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: admin_suite_q_access_info
      Role: !GetAtt QuickAdminSuiteRole.Arn
      Timeout: 120
      WorkerType: G.1X
      NumberOfWorkers: 2
    DependsOn:
      - admin_suite_qs_md
  admin_suite_q_topic__def_info:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        PythonVersion: '3'
        ScriptLocation: !Sub s3://admin-console-cfn-dataprepare-code/glue/scripts/2025/admin_suite_q_topic__def_info.py
      DefaultArguments:
        '--AWS_REGION': !Sub ${AWS::Region}
        '--AWS_ACCOUNT_ID': !Sub ${AWS::AccountId}
        '--S3_OUTPUT_PATH': !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/q_topics_info
      GlueVersion: '5.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: admin_suite_q_topic__def_info
      Role: !GetAtt QuickAdminSuiteRole.Arn
      Timeout: 120
      WorkerType: G.1X
      NumberOfWorkers: 2
    DependsOn:
      - admin_suite_qs_md
  admin_suite_qs_access_info_schedule:
    Type: AWS::Glue::Trigger
    Properties:
      Type: SCHEDULED
      Description: Glue Trigger to run admin_suite_qs_access_info glue job every 3 hours
      Schedule: cron(0 */3 * * ? *)
      Actions:
        - JobName: admin_suite_qs_access_info
      Name: admin_suite_qs_access_info-every-3-hour
      StartOnCreation: true
  admin_suite_dataset_dashboard_info_schedule:
    Type: AWS::Glue::Trigger
    Properties:
      Type: SCHEDULED
      Description: Glue Trigger to run admin_suite_dataset_dashboard_info glue job every
        3 hours
      Schedule: cron(0 */3 * * ? *)
      Actions:
        - JobName: admin_suite_dataset_dashboard_info
      Name: admin_suite_dataset_dashboard_info-every-3-hour
      StartOnCreation: true
  admin_suite_folder_info_schedule:
    Type: AWS::Glue::Trigger
    Properties:
      Type: SCHEDULED
      Description: Glue Trigger to run admin_suite_folder_info job every 3 hours
      Schedule: cron(0 */3 * * ? *)
      Actions:
        - JobName: admin_suite_folder_info
      Name: admin_suite_folder_info-every-3-hour
      StartOnCreation: true
  admin_suite_q_topic__def_info_schedule:
    Type: AWS::Glue::Trigger
    Properties:
      Type: SCHEDULED
      Description: Glue Trigger to run admin_suite_q_topic__def_info glue job every 3 hours
      Schedule: cron(0 */3 * * ? *)
      Actions:
        - JobName: admin_suite_q_topic__def_info
      Name: admin_suite_q_topic__def_info-every-3-hour
      StartOnCreation: true
  admin_suite_q_access_info_schedule:
    Type: AWS::Glue::Trigger
    Properties:
      Type: SCHEDULED
      Description: Glue Trigger to run admin_suite_q_access_info glue job every 3 hours
      Schedule: cron(0 */3 * * ? *)
      Actions:
        - JobName: admin_suite_q_access_info
      Name: admin_suite_q_access_info-every-3-hour
      StartOnCreation: true
  admin_suite_qs_md:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: !Join
        - ''
        - - admin_suite_qs_md_
          - !Ref AWS::AccountId
Outputs:
  groupmembership:
    Description: The s3 location of group_membership.csv for you to utilize in next
      Athena tables creation stack
    Value: !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/group_membership
  objectaccess:
    Description: The s3 location of object_access.csv for you to utilize in next
      Athena tables creation stack
    Value: !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/object_access
  folderassets:
    Description: The s3 location of folder_assets.csv for you to utilize in next
      Athena tables creation stack
    Value: !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/folder_assets/folder_assets.csv
  folderlk:
    Description: The s3 location of folder_lk.csv for you to utilize in next Athena
      tables creation stack
    Value: !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/folder_lk/folder_lk.csv
  folderpath:
    Description: The s3 location of folder_path.csv for you to utilize in next
      Athena tables creation stack
    Value: !Sub s3://admin-console-new-${AWS::AccountId}/monitoring/quicksight/folder_path/folder_path.csv
  cloudtraillogtablename:
    Description: The table name of cloudtrail log for you to utilize in next Athena
      tables creation stack
    Value: cloudtrail_logs
  cloudtraillog:
    Description: The s3 location of cloudtrail log for you to utilize in next Athena
      tables creation stack
    Value: !Sub s3://cloudtrail-awslogs-${AWS::AccountId}-do-not-delete/AWSLogs/${AWS::AccountId}/CloudTrail
Metadata:
  AWS::CloudFormation::Designer:
    494a8dba-26e5-4efa-93ea-d49a84c99390:
      size:
        width: 60
        height: 60
      position:
        x: -130
        'y': 230
      z: 1
      embeds: []
    137f8de2-0d45-4490-a6a7-04356c185c4a:
      size:
        width: 60
        height: 60
      position:
        x: 20
        'y': 240
      z: 1
      embeds: []
    c4462e36-ef27-43d6-a0df-01246a77b117:
      size:
        width: 60
        height: 60
      position:
        x: 10
        'y': 70
      z: 1
      embeds: []
      dependson:
        - 494a8dba-26e5-4efa-93ea-d49a84c99390
    2d875ca8-973f-4c0c-8455-1f15eb588bdb:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 210
      z: 1
      embeds: []
    a59461e8-9fcb-415c-b8a0-0f21f2b4e38b:
      size:
        width: 60
        height: 60
      position:
        x: 400
        'y': 100
      z: 1
      embeds: []
      isassociatedwith:
        - c4462e36-ef27-43d6-a0df-01246a77b117
    f2b566cb-22e3-41b5-a520-ec2c86a63929:
      size:
        width: 60
        height: 60
      position:
        x: 20
        'y': 400
      z: 1
      embeds: []
      dependson:
        - 494a8dba-26e5-4efa-93ea-d49a84c99390
    50816f94-5ba8-4b3b-91da-84afa96bd9e7:
      size:
        width: 60
        height: 60
      position:
        x: 410
        'y': 360
      z: 1
      embeds: []
      isassociatedwith:
        - f2b566cb-22e3-41b5-a520-ec2c86a63929